name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source
      - uses: actions/checkout@v3

      # 2. Set up Java 21
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Import GPG key
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --batch --import
          gpg --list-secret-keys

      # 4. Build and run tests
      - name: Build with tests
        run: mvn --batch-mode --update-snapshots verify

      # 5. Configure Git for release
      - name: Configure Git user
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"

      # 6. Prepare Maven release
      - name: Release prepare
        run: mvn -B release:prepare

      # 7. Publish to Central
      - name: Publish to Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${SONATYPE_USERNAME}</username>
                <password>${SONATYPE_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

          mvn central:publish \
            -Dgpg.passphrase=$GPG_PASSPHRASE

      # 8. Perform Maven release
      - name: Release perform
        run: mvn release:perform -Darguments="-Dmaven.deploy.skip=true"
